sudo: required
dist: bionic
language: generic
services:
  - docker
arch:
  - arm64
os: linux

env:
  - ROS_DISTRO=kinetic
  - ROS_DISTRO=melodic
  - ROS_DISTRO=melodic-py3
  - ROS_DISTRO=noetic

script:
  - pushd ${ROS_DISTRO}
  - docker build --rm --tag=sfalexrog/rpi-ros:${ROS_DISTRO}-core .
  - popd

after_success:
  - >
    if [ "${TRAVIS_BRANCH}" == "master" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker push "sfalexrog/rpi-ros:${ROS_DISTRO}-core"
    fi
